create extension if not exists vector;

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  document_name text not null,
  document_type text not null,
  record_id text not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(1536) not null,
  created_at timestamptz not null default now(),
  unique(document_name, record_id)
);

create index if not exists documents_embedding_idx
on public.documents using ivfflat (embedding vector_cosine_ops) with (lists = 10);

create or replace function public.match_documents(query_embedding vector(1536), match_count int default 5)
returns table(id bigint, document_name text, document_type text, record_id text,
              content text, metadata jsonb, similarity double precision)
language sql stable as $$
  select d.id, d.document_name, d.document_type, d.record_id, d.content, d.metadata,
         (1 - (d.embedding <=> query_embedding))::double precision as similarity
  from public.documents d
  order by d.embedding <=> query_embedding
  limit greatest(match_count, 1);
$$;

alter table public.documents enable row level security;
-- Configure read policies/roles for your deployment. Never grant anonymous writes.
